// This file will be auto-generated by Supabase CLI
// For now, we'll add basic types manually

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string
          phone: string | null
          role: 'admin' | 'cleaner' | 'property_manager'
          avatar_url: string | null
          is_active: boolean
          is_approved: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name: string
          phone?: string | null
          role: 'admin' | 'cleaner' | 'property_manager'
          avatar_url?: string | null
          is_active?: boolean
          is_approved?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string
          phone?: string | null
          role?: 'admin' | 'cleaner' | 'property_manager'
          avatar_url?: string | null
          is_active?: boolean
          is_approved?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      properties: {
        Row: {
          id: string
          name: string
          address: string
          gps_lat: number | null
          gps_lng: number | null
          access_instructions: string | null
          size_sqm: number | null
          bedrooms: number | null
          bathrooms: number | null
          property_manager_id: string | null
          ical_airbnb: string | null
          ical_booking: string | null
          ical_other: string | null
          default_cleaning_type: string
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          address: string
          gps_lat?: number | null
          gps_lng?: number | null
          access_instructions?: string | null
          size_sqm?: number | null
          bedrooms?: number | null
          bathrooms?: number | null
          property_manager_id?: string | null
          ical_airbnb?: string | null
          ical_booking?: string | null
          ical_other?: string | null
          default_cleaning_type?: string
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          address?: string
          gps_lat?: number | null
          gps_lng?: number | null
          access_instructions?: string | null
          size_sqm?: number | null
          bedrooms?: number | null
          bathrooms?: number | null
          property_manager_id?: string | null
          ical_airbnb?: string | null
          ical_booking?: string | null
          ical_other?: string | null
          default_cleaning_type?: string
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      cleanings: {
        Row: {
          id: string
          property_id: string
          cleaner_id: string | null
          cleaning_type_id: string | null
          status: 'pending' | 'assigned' | 'in_progress' | 'completed' | 'cancelled'
          scheduled_date: string
          scheduled_time: string | null
          started_at: string | null
          completed_at: string | null
          is_urgent: boolean
          is_manual: boolean
          ical_event_uid: string | null
          ical_platform: 'airbnb' | 'booking' | 'other' | null
          guest_rejected: boolean
          guest_signature_url: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          property_id: string
          cleaner_id?: string | null
          cleaning_type_id?: string | null
          status?: 'pending' | 'assigned' | 'in_progress' | 'completed' | 'cancelled'
          scheduled_date: string
          scheduled_time?: string | null
          started_at?: string | null
          completed_at?: string | null
          is_urgent?: boolean
          is_manual?: boolean
          ical_event_uid?: string | null
          ical_platform?: 'airbnb' | 'booking' | 'other' | null
          guest_rejected?: boolean
          guest_signature_url?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          property_id?: string
          cleaner_id?: string | null
          cleaning_type_id?: string | null
          status?: 'pending' | 'assigned' | 'in_progress' | 'completed' | 'cancelled'
          scheduled_date?: string
          scheduled_time?: string | null
          started_at?: string | null
          completed_at?: string | null
          is_urgent?: boolean
          is_manual?: boolean
          ical_event_uid?: string | null
          ical_platform?: 'airbnb' | 'booking' | 'other' | null
          guest_rejected?: boolean
          guest_signature_url?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      cleaning_types: {
        Row: {
          id: string
          name: string
          description: string | null
          base_price: number
          estimated_duration_minutes: number
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          description?: string | null
          base_price: number
          estimated_duration_minutes: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          description?: string | null
          base_price?: number
          estimated_duration_minutes?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      cleaning_extras: {
        Row: {
          id: string
          name: string
          description: string | null
          price: number
          is_active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          description?: string | null
          price: number
          is_active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          description?: string | null
          price?: number
          is_active?: boolean
          created_at?: string
        }
      }
      cleaning_selected_extras: {
        Row: {
          id: string
          cleaning_id: string
          extra_id: string
          quantity: number
          created_at: string
        }
        Insert: {
          id?: string
          cleaning_id: string
          extra_id: string
          quantity?: number
          created_at?: string
        }
        Update: {
          id?: string
          cleaning_id?: string
          extra_id?: string
          quantity?: number
          created_at?: string
        }
      }
      cleaning_checklists: {
        Row: {
          id: string
          cleaning_id: string
          template_id: string | null
          checklist_data: Json
          completed_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          cleaning_id: string
          template_id?: string | null
          checklist_data: Json
          completed_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          cleaning_id?: string
          template_id?: string | null
          checklist_data?: Json
          completed_at?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      cleaning_images: {
        Row: {
          id: string
          cleaning_id: string
          image_url: string
          image_type: 'before' | 'after' | 'damage' | 'lost_item'
          checklist_item_id: string | null
          notes: string | null
          created_at: string
        }
        Insert: {
          id?: string
          cleaning_id: string
          image_url: string
          image_type: 'before' | 'after' | 'damage' | 'lost_item'
          checklist_item_id?: string | null
          notes?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          cleaning_id?: string
          image_url?: string
          image_type?: 'before' | 'after' | 'damage' | 'lost_item'
          checklist_item_id?: string | null
          notes?: string | null
          created_at?: string
        }
      }
      checklist_templates: {
        Row: {
          id: string
          name: string
          description: string | null
          cleaning_type_id: string | null
          items: Json
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          description?: string | null
          cleaning_type_id?: string | null
          items: Json
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          description?: string | null
          cleaning_type_id?: string | null
          items?: Json
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      damage_catalog: {
        Row: {
          id: string
          name: string
          description: string | null
          category: string
          estimated_price: number
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          description?: string | null
          category: string
          estimated_price: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          description?: string | null
          category?: string
          estimated_price?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      damage_reports: {
        Row: {
          id: string
          cleaning_id: string
          catalog_item_id: string | null
          description: string
          severity: 'low' | 'medium' | 'high'
          status: 'pending' | 'reviewed' | 'resolved' | 'charged'
          estimated_cost: number | null
          actual_cost: number | null
          image_urls: string[]
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          cleaning_id: string
          catalog_item_id?: string | null
          description: string
          severity?: 'low' | 'medium' | 'high'
          status?: 'pending' | 'reviewed' | 'resolved' | 'charged'
          estimated_cost?: number | null
          actual_cost?: number | null
          image_urls?: string[]
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          cleaning_id?: string
          catalog_item_id?: string | null
          description?: string
          severity?: 'low' | 'medium' | 'high'
          status?: 'pending' | 'reviewed' | 'resolved' | 'charged'
          estimated_cost?: number | null
          actual_cost?: number | null
          image_urls?: string[]
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      lost_item_reports: {
        Row: {
          id: string
          cleaning_id: string
          item_name: string
          description: string | null
          location_found: string | null
          status: 'pending' | 'stored' | 'returned' | 'disposed'
          image_urls: string[]
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          cleaning_id: string
          item_name: string
          description?: string | null
          location_found?: string | null
          status?: 'pending' | 'stored' | 'returned' | 'disposed'
          image_urls?: string[]
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          cleaning_id?: string
          item_name?: string
          description?: string | null
          location_found?: string | null
          status?: 'pending' | 'stored' | 'returned' | 'disposed'
          image_urls?: string[]
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      notifications: {
        Row: {
          id: string
          user_id: string
          type: string
          title: string
          message: string | null
          data: Json | null
          read: boolean
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          type: string
          title: string
          message?: string | null
          data?: Json | null
          read?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          type?: string
          title?: string
          message?: string | null
          data?: Json | null
          read?: boolean
          created_at?: string
        }
      }
      conversations: {
        Row: {
          id: string
          participant_1_id: string
          participant_2_id: string
          last_message_text: string | null
          last_message_at: string | null
          last_message_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          participant_1_id: string
          participant_2_id: string
          last_message_text?: string | null
          last_message_at?: string | null
          last_message_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          participant_1_id?: string
          participant_2_id?: string
          last_message_text?: string | null
          last_message_at?: string | null
          last_message_by?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      messages: {
        Row: {
          id: string
          conversation_id: string
          sender_id: string
          content: string
          read_at: string | null
          related_cleaning_id: string | null
          related_damage_report_id: string | null
          related_lost_item_id: string | null
          created_at: string
        }
        Insert: {
          id?: string
          conversation_id: string
          sender_id: string
          content: string
          read_at?: string | null
          related_cleaning_id?: string | null
          related_damage_report_id?: string | null
          related_lost_item_id?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          conversation_id?: string
          sender_id?: string
          content?: string
          read_at?: string | null
          related_cleaning_id?: string | null
          related_damage_report_id?: string | null
          related_lost_item_id?: string | null
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
