// This file will be auto-generated by Supabase CLI
// For now, we'll add basic types manually

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string
          phone: string | null
          role: 'admin' | 'cleaner' | 'property_manager'
          avatar_url: string | null
          is_active: boolean
          is_approved: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name: string
          phone?: string | null
          role: 'admin' | 'cleaner' | 'property_manager'
          avatar_url?: string | null
          is_active?: boolean
          is_approved?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string
          phone?: string | null
          role?: 'admin' | 'cleaner' | 'property_manager'
          avatar_url?: string | null
          is_active?: boolean
          is_approved?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      properties: {
        Row: {
          id: string
          name: string
          address: string
          gps_lat: number | null
          gps_lng: number | null
          access_instructions: string | null
          size_sqm: number | null
          bedrooms: number | null
          bathrooms: number | null
          property_manager_id: string | null
          ical_airbnb: string | null
          ical_booking: string | null
          ical_other: string | null
          default_cleaning_type: string
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          address: string
          gps_lat?: number | null
          gps_lng?: number | null
          access_instructions?: string | null
          size_sqm?: number | null
          bedrooms?: number | null
          bathrooms?: number | null
          property_manager_id?: string | null
          ical_airbnb?: string | null
          ical_booking?: string | null
          ical_other?: string | null
          default_cleaning_type?: string
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          address?: string
          gps_lat?: number | null
          gps_lng?: number | null
          access_instructions?: string | null
          size_sqm?: number | null
          bedrooms?: number | null
          bathrooms?: number | null
          property_manager_id?: string | null
          ical_airbnb?: string | null
          ical_booking?: string | null
          ical_other?: string | null
          default_cleaning_type?: string
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      cleanings: {
        Row: {
          id: string
          property_id: string
          cleaner_id: string | null
          cleaning_type_id: string | null
          status: 'pending' | 'assigned' | 'in_progress' | 'completed' | 'cancelled'
          scheduled_date: string
          scheduled_time: string | null
          started_at: string | null
          completed_at: string | null
          is_urgent: boolean
          is_manual: boolean
          ical_event_uid: string | null
          ical_platform: 'airbnb' | 'booking' | 'other' | null
          guest_rejected: boolean
          guest_signature_url: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          property_id: string
          cleaner_id?: string | null
          cleaning_type_id?: string | null
          status?: 'pending' | 'assigned' | 'in_progress' | 'completed' | 'cancelled'
          scheduled_date: string
          scheduled_time?: string | null
          started_at?: string | null
          completed_at?: string | null
          is_urgent?: boolean
          is_manual?: boolean
          ical_event_uid?: string | null
          ical_platform?: 'airbnb' | 'booking' | 'other' | null
          guest_rejected?: boolean
          guest_signature_url?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          property_id?: string
          cleaner_id?: string | null
          cleaning_type_id?: string | null
          status?: 'pending' | 'assigned' | 'in_progress' | 'completed' | 'cancelled'
          scheduled_date?: string
          scheduled_time?: string | null
          started_at?: string | null
          completed_at?: string | null
          is_urgent?: boolean
          is_manual?: boolean
          ical_event_uid?: string | null
          ical_platform?: 'airbnb' | 'booking' | 'other' | null
          guest_rejected?: boolean
          guest_signature_url?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      // Add more tables as needed
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
